name: Atualizar Dashboard Vesti

on:
  schedule:
    - cron: '0 8 * * *' # Roda todos os dias às 08:00 AM UTC
  workflow_dispatch: # Permite que você rode manualmente clicando num botão

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: |
          pip install pandas numpy statsmodels scikit-learn

      - name: Rodar Pipeline
        run: python pipeline.py

      - name: Enviar mudanças de volta ao repositório
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add dados_dashboard.json
          git commit -m "Automação: Atualizando dados do dashboard"
          git push